Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, Jenkinsfile, docker-compose.advanced.yml.sample, docker-compose.basic.yml.sample, readme-vars.yml, root/etc/cont-init.d/50-config
Added logic for 'advanced mode' to allow direct editing of the .env file
Fixed symlinking issues
Fixed appurl variable issue (for basic mode users) - resolves issue #7 
Updated Jenkinsfile
=> Modifications to make container release ready 

README.md
This fixes a SQL syntax error experienced when using the LinuxServer MariaDB container.
[Here is an example](https://i.imgur.com/rez6DtD.png) that shows both the error and that it is fixed by the introduction of ' around %) (I am using `hass` in place of `myuser` because I'm using it for Home Assistant -- but that's irrelevant).
=> fix SQL command syntax in Application Setup command

readme-vars.yml
=> fixing typos and mistakes in readme-vars 

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, README.md, readme-vars.yml
BookStack has built-in support for `wkhtmltopdf`, but it must be installed on the system or be added to the application directory. 
This PR adds the dependencies and `wkhtmltopdf` itself from the alpine test repo.
Users of the image can then modify their instance's `.env` file to use wkhtmltopdf instead as described in the [BookStack documentation](https://www.bookstackapp.com/docs/admin/pdf-rendering/)
IE: `WKHTMLTOPDF=/usr/bin/wkhtmltopdf`
=> Add WKHTMLTOPDF for use in .env file if desired

readme-vars.yml
example is incorrect, now fixed.
=> FIX APP_URL with correct example

Dockerfile, Dockerfile.aarch64, README.md, readme-vars.yml
Alpine 3.7 does not have armv7 libs so we are SOL there, but this should fix the issue for most users pending upstream: 
https://github.com/BookStackApp/BookStack/issues/1553
=> #33 update x86 and aarch64 to use old version of tidyhtml

root/etc/cont-init.d/50-config
also formatted "do" and "then" in this section for style consistency
closes #31
=> skip mysql endpoint check if DB_HOST is empty

root/etc/cont-init.d/50-config
We welcome all PR’s though this doesn’t guarantee it will be accepted.
Looking at the following line, I can see why `APP_URL` is not being applied in `/config/www/.env`
```shell
[[ "${APP_URL}" ]] && sed -i "s,#\sAPP_URL.*,APP_URL=${APP_URL},g" /config/www/.env
```
This substitution is expecting `# APP_URL` but the example env file doesn't include a space: `#APP_URL`.
The workaround is to manually edit your `/config/www/.env` file and avoid providing environment variables that would cause it to be overwritten.
Fixes one of the symptoms described in …
=> fix substitution of APP_URL when provided

root/etc/cont-init.d/50-config
Updates grep to not be both regex & string pattern match to prevent mis-matching of line, also changes "MB" to PHP standard "M"
If this isn't fixed, all posts & logins seem to fail
It also leads to duplication infinitely every restart
Ran the scripts local in the container to verify functionality in the container.
https://discordapp.com/channels/354974912613449730/506925392603512839/756980418795798558
=> Resolving php-local.ini mangling

README.md, readme-vars.yml, root/etc/cont-init.d/50-config
=> make APP_URL required, detect changes

root/etc/cont-init.d/50-config
Escape special characters in DB_PASSWORD environment variable before they're used in a sed substitution.
A `DB_PASS` variable containing any of the following characters will not be output verbatim in a sed replacement string: 
- /
- \
- &
- $
Causing Bookstack initialisations to fail as the DB and Web App are provided with different passwords.
Tested in Bash/Zsh:
Old Behaviour:
```bash
matt@matt-pc ~/ $ echo 'DB_PASSWORD=database_user_password' > regex_test.env
matt@matt-pc ~/ $ cat regex_test.env 
DB_PASSWORD=database_user_password …
```
=> Escape special characters in DB_PASS environment variable when substituting with sed

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, Jenkinsfile, README.md, jenkins-vars.yml, readme-vars.yml
Rebase to 3.14
Update formatting
Remove tidyhtml fix as per https://github.com/BookStackApp/BookStack/issues/1565#issuecomment-778491951
Install composer from Alpine repos instead of direct from their site as they have version parity
Add EXPOSE statement
Tested locally with existing install
=> Rebase to 3.14

root/etc/cont-init.d/50-config
Following #106 it is no longer possible to mount a custom themes folder into the container - doing so causes the container to fail to load.
This PR extends the existing config symlink mechanism to link /var/www/html/themes to /config/www/themes, enabling custom themes to be used again
Closes #108 
Tested locally with existing install
=> Create themes folder in config folder and symlink to it

root/etc/cont-init.d/50-config
We improved the match in mariadb itself but not other containers, this will align the sed for mariadb and dbpass in bookstack while also improving the actual sed itself.
=> Improve sed and maintain consistency with other database password sed 

README.md, readme-vars.yml, root/etc/cont-init.d/50-config
We have had some infrequent complaints about DB_PASS not working at times. Unfortunately, the users who complain never provide any relevant detail that allows us to work to resolve the issue. The logic in this is to attempt to escape special characters in the password before feeding it into the database, the users who have the issue erroneously believe that db_password is the right var because of a lack of understanding, however, this does indicate that bypassing our escape logic is a potential solution. I did some testing with various passwords and had no issues by removing our escape logic at all. 
If this works, we will want to replicate this PR to mariadb and other containers with a similar var and escape logic.
=> Remove db_pass escape logic

README.md, readme-vars.yml, root/etc/cont-init.d/50-config
=> fix db password setting (sed escape &)

Dockerfile, Dockerfile.aarch64, Dockerfile.armhf, readme-vars.yml
This adds the `iconv` PHP extension to the build scripts since the iconv php extension is a requirement for BookStack that has previously been poly-filled but is now needed as an extension. 
See https://github.com/linuxserver/docker-bookstack/issues/162 for more detail. 
This adds a required extension that's needed in certain features of BookStack, such as QR code generation for TOTP MFA. 
I build a fresh image for the modified files, then used that in a compose setup to check the image worked, at that the error produced from the lack of the …
=> Added php81-iconv as an installed php extension

readme-vars.yml
This adds details of how BookStack files and folders within the container `/config` volume relate to those within a default BookStack installation.
Related to #167.
The default file/folder names used within the mounted `/config` folder only match those within a BookStack installation by name, and they can be tricky to understand without understanding how these are linked within the container. Users can often need to know/use these files and directories when following BookStack documentation, for things like migrations from non-docker …
=> Added file/folder path mapping to readme

README.md, readme-vars.yml
- [O] I have read the [contributing](https://github.com/linuxserver/docker-bookstack/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications
Update README to match the password requirement with dependency. Per mariadb image, the required DATABASE_PASSWORD must be greater than 4 characters.
New user who sets password less than 4 char will cause error similar to database connection issue where previous issues are all arguing DB_PASS or DB_PASSWORD which is not the solution here.
In short, it is …
=> Update password restriction matching to db image manual

Dockerfile, Dockerfile.aarch64, README.md, readme-vars.yml, root/etc/s6-overlay/s6-rc.d/svc-queue-worker/run, root/etc/s6-overlay/s6-rc.d/svc-queue-worker/type, root/init-hook
=> Add async action support

README.md, readme-vars.yml
=> Tidy readme

Dockerfile, Dockerfile.aarch64, jenkins-vars.yml, readme-vars.yml
=> Add php83-exif for reading image EXIF data

README.md, readme-vars.yml, root/appkey, root/etc/s6-overlay/s6-rc.d/init-bookstack-config/run
=> Fix appkey check + add helper

README.md, readme-vars.yml, root/etc/s6-overlay/s6-rc.d/init-bookstack-config/run
=> Attempt to remove any and all ambiguity from the readme instructions.

Dockerfile, Dockerfile.aarch64, README.md, readme-vars.yml, root/etc/s6-overlay/s6-rc.d/init-bookstack-config/run
For some reason there's a permissions issue with Laravel if we try and put the session/cache config into tmpfs, hence having to put it in /config and clearing it on startup.
=> Rebase to 3.21, support read-only operation
